version: '2'

services:
  web:
    image: nginx:latest
    container_name: code_web
    ports:
      - "8090:90"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code
  php:
    container_name: code_php
    build:
      context: ""
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
    networks:
      - code
  postgres:
    container_name: code_postgres
    image: postgres:11
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    networks:
      - code
    volumes:
      - ./postgres/:/var/lib/postgresql/data

networks:
  code:
    driver: bridge